---
server:
  port: 9002
spring:
  application:
    name: Order-Service
  config.activate.on-profile: default
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  main:
    allow-circular-references: true

solace:
  reconnectionAttempts: "5"
  connectionRetriesPerHost: "5"
  orderCreatedEventTopicString: "acmeretail/onlineservices/order/created/v2/{regionId}/{orderId}"
  orderUpdatesQueueName: "all-order-updates"